# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "browserify-13.3.0" = {
      name = "browserify";
      packageName = "browserify";
      version = "13.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-13.3.0.tgz";
        sha1 = "b5a9c9020243f0c70e4675bec8223bc627e415ce";
      };
    };
    "browserify-incremental-3.1.1" = {
      name = "browserify-incremental";
      packageName = "browserify-incremental";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-incremental/-/browserify-incremental-3.1.1.tgz";
        sha1 = "0713cb7587247a632a9f08cf1bd169b878b62a8a";
      };
    };
    "concat-stream-1.6.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.0.tgz";
        sha1 = "0aac662fd52be78964d5532f694784e70110acf7";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "node-static-0.7.10" = {
      name = "node-static";
      packageName = "node-static";
      version = "0.7.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-static/-/node-static-0.7.10.tgz";
        sha512 = "3a22r0jr4112h0vr1smzrsaygc607v13arhjbjwzmy1jvmcrdlq9ydnw96ailkrlnwl3k0l65hjcgnrgkdwyc2qhbfnq2bgk0xz7pkd";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "string-stream-0.0.7" = {
      name = "string-stream";
      packageName = "string-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-stream/-/string-stream-0.0.7.tgz";
        sha1 = "cfcde82799fa62f303429aaa79336ee8834332fe";
      };
    };
    "temp-0.8.3" = {
      name = "temp";
      packageName = "temp";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp/-/temp-0.8.3.tgz";
        sha1 = "e0c6bc4d26b903124410e4fed81103014dfc1f59";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tree-kill-1.2.0" = {
      name = "tree-kill";
      packageName = "tree-kill";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tree-kill/-/tree-kill-1.2.0.tgz";
        sha512 = "1r0mixygpdqrm2fn92z4cyxzbnvimm16k5gdm2m2jxx8wrj3w0mql9s748hcqp2nzcnybnw74wkm211zlr9ld0j2x1q8f153mszlm8f";
      };
    };
    "watchpack-1.4.0" = {
      name = "watchpack";
      packageName = "watchpack";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/watchpack/-/watchpack-1.4.0.tgz";
        sha1 = "4a1472bcbb952bd0a9bb4036801f954dfb39faac";
      };
    };
    "which-1.3.0" = {
      name = "which";
      packageName = "which";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.0.tgz";
        sha512 = "358cfi3qak701qp5pwkq47n87ca4m8k4lvjl0pdybvmp92nwwd7azzhahy9gy3kg8lqrqdry9l6pl2csflzr0nvwnc3p6asjyi6khn5";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "JSONStream-1.3.2" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.2.tgz";
        sha1 = "c102371b6ec3a7cf3b847ca00c20bb0fce4c6dea";
      };
    };
    "assert-1.4.1" = {
      name = "assert";
      packageName = "assert";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.4.1.tgz";
        sha1 = "99912d591836b5a6f5b345c0f07eefc08fc65d91";
      };
    };
    "browser-pack-6.0.2" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-6.0.2.tgz";
        sha1 = "f86cd6cef4f5300c8e63e07a4d512f65fbff4531";
      };
    };
    "browser-resolve-1.11.2" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.2.tgz";
        sha1 = "8ff09b0a2c421718a1051c260b32e48f442938ce";
      };
    };
    "browserify-zlib-0.1.4" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.1.4.tgz";
        sha1 = "bb35f8a519f600e0fa6b8485241c979d0141fb2d";
      };
    };
    "buffer-4.9.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "4.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-4.9.1.tgz";
        sha1 = "6d1bb601b07a4efced97094132093027c95bc298";
      };
    };
    "cached-path-relative-1.0.1" = {
      name = "cached-path-relative";
      packageName = "cached-path-relative";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cached-path-relative/-/cached-path-relative-1.0.1.tgz";
        sha1 = "d09c4b52800aa4c078e2dd81a869aac90d2e54e7";
      };
    };
    "concat-stream-1.5.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.2.tgz";
        sha1 = "708978624d856af41a5a741defdd261da752c266";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "constants-browserify-1.0.0" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz";
        sha1 = "c20b96d8c617748aaf1c16021760cd27fcb8cb75";
      };
    };
    "crypto-browserify-3.12.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.12.0.tgz";
        sha512 = "1d3mrhqlay037azmjp2ml5a8yyls9ijdhilv6f0znz0ajgfm972yr9bhm78wqi09p4crc3shgflk50jc63zijsqv777ikkyi2j2qgkz";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-2.0.0" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-2.0.0.tgz";
        sha1 = "091724902e84658260eb910748cccd1af6e21fb5";
      };
    };
    "domain-browser-1.1.7" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.1.7.tgz";
        sha1 = "867aa4b093faa05f1de08c06f4d7b21fdf8698bc";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "events-1.1.1" = {
      name = "events";
      packageName = "events";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-1.1.1.tgz";
        sha1 = "9ebdb7635ad099c70dcc4c2a1f5004288e8bd924";
      };
    };
    "has-1.0.1" = {
      name = "has";
      packageName = "has";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.1.tgz";
        sha1 = "8461733f538b0837c9361e39a9ab9e9704dc2f28";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "https-browserify-0.0.1" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-0.0.1.tgz";
        sha1 = "3f91365cabe60b77ed0ebba24b454e3e09d95a82";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "insert-module-globals-7.0.1" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.0.1.tgz";
        sha1 = "c03bf4e01cb086d5b5e5ace8ad0afe7889d638c3";
      };
    };
    "labeled-stream-splicer-2.0.0" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-2.0.0.tgz";
        sha1 = "a52e1d138024c00b86b1c0c91f677918b8ae0a59";
      };
    };
    "module-deps-4.1.1" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-4.1.1.tgz";
        sha1 = "23215833f1da13fd606ccb8087b44852dcb821fd";
      };
    };
    "os-browserify-0.1.2" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.1.2.tgz";
        sha1 = "49ca0293e0b19590a5f5de10c7f265a617d8fe54";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "path-browserify-0.0.0" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.0.tgz";
        sha1 = "a0b870729aae214005b7d5032ec2cbbb0fb4451a";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "read-only-stream-2.0.0" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-2.0.0.tgz";
        sha1 = "2724fd6a8113d73764ac288d4386270c1dbf17f0";
      };
    };
    "readable-stream-2.3.3" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.3.tgz";
        sha512 = "1wlizkv2wnz2nyb0lfxgs1m27zzcvasp3n5cfrd7hm4ch1wn79df2nbhzfadba5qqdfb28vhmw3drhp46vk2q6xk524qagvr76v7slv";
      };
    };
    "resolve-1.5.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.5.0.tgz";
        sha512 = "25scf9zkhf5yc9x3d7mfq2im5vyxmq3ih939na6jzblal7mgfcijmadl2maz501mkccykj714gvdhhmlzi86hbk7k03r9ipnwd142l6";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shell-quote-1.6.1" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.6.1.tgz";
        sha1 = "f4781949cce402697127430ea3b3c5476f481767";
      };
    };
    "stream-browserify-2.0.1" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.1.tgz";
        sha1 = "66266ee5f9bdb9940a4e4514cafb43bb71e5c9db";
      };
    };
    "stream-http-2.7.2" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "2.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-2.7.2.tgz";
        sha512 = "09n1hj53jy075fnbsaaiknry7in0l4yarh912abwgvk4hwl33lvn8wrfw891zg5bkfa7sxlmd5yz3xxd4dmcln19bnkahyvd87r6k3k";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "syntax-error-1.3.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.3.0.tgz";
        sha1 = "1ed9266c4d40be75dc55bf9bb1cb77062bb96ca1";
      };
    };
    "through2-2.0.3" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.3.tgz";
        sha1 = "0004569b37c7c74ba39c43f3ced78d1ad94140be";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tty-browserify-0.0.0" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.0.tgz";
        sha1 = "a157ba402da24e9bf957f9aa69d524eed42901a6";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "vm-browserify-0.0.4" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz";
        sha1 = "5d7ea45bbef9e4a6ff65f95438e0a87c357d5a73";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "combine-source-map-0.7.2" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.7.2.tgz";
        sha1 = "0870312856b307a87cc4ac486f3a9a62aeccc09e";
      };
    };
    "umd-3.0.1" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.1.tgz";
        sha1 = "8ae556e11011f63c2596708a8837259f01b3d60e";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "inline-source-map-0.6.2" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.6.2.tgz";
        sha1 = "f9393471c18a79d1724f863fa38b586370ade2a5";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha1 = "f3f7522f4ef782348da8161bad9ecfd51bf83a75";
      };
    };
    "base64-js-1.2.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.2.1.tgz";
        sha512 = "0dhi66vsajfcm04s11xqklh5lj3abs4ncnl8h3689964aqam3ps9spmc454hz94rz3x1x5l1ad03jrba67mq9zc9vq9a1gchma581bp";
      };
    };
    "ieee754-1.1.8" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz";
        sha1 = "be33d40ac10ef1926701f6f08a2d86fbfd1ad3e4";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "browserify-cipher-1.0.0" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.0.tgz";
        sha1 = "9988244874bf5ed4e28da95666dcd66ac8fc363a";
      };
    };
    "browserify-sign-4.0.4" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.0.4.tgz";
        sha1 = "aa4eb68e5d7b658baa6bf6a57e630cbd7a93d298";
      };
    };
    "create-ecdh-4.0.0" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.0.tgz";
        sha1 = "888c723596cdf7612f6498233eebd7a35301737d";
      };
    };
    "create-hash-1.1.3" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.1.3.tgz";
        sha1 = "606042ac8b9262750f483caddab0f5819172d8fd";
      };
    };
    "create-hmac-1.1.6" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.6.tgz";
        sha1 = "acb9e221a4e17bdb076e90657c42b93e3726cf06";
      };
    };
    "diffie-hellman-5.0.2" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.2.tgz";
        sha1 = "b5835739270cfe26acf632099fded2a07f209e5e";
      };
    };
    "pbkdf2-3.0.14" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.14.tgz";
        sha512 = "30bb7vx0m1k1m3d1i1khgvmgddx3ahqgprs421ssrh5plpx50k5bazsj67gdi7qiknircqy59yxbclq95s2rnmk8ysgkqdpsddijfw2";
      };
    };
    "public-encrypt-4.0.0" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.0.tgz";
        sha1 = "39f699f3a46560dd5ebacbca693caf7c65c18cc6";
      };
    };
    "randombytes-2.0.5" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.0.5.tgz";
        sha512 = "293m4ffiafbjg0b99a2k78wiffmlwc2v7cigrn5l3n7555x7qxyr34sp0s4p713vwlaf0ny5n57iysgkz08slld3hzw8ci1a2gxjgpi";
      };
    };
    "randomfill-1.0.3" = {
      name = "randomfill";
      packageName = "randomfill";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomfill/-/randomfill-1.0.3.tgz";
        sha512 = "08l7hdx65kfxli7g9pcnlv84bdrccj7d267d1kfi93db6a4mihwyhvsipmx2n0yk9z45cs21isgpld6rib5saxg28s2g8nn3ap8dgk0";
      };
    };
    "browserify-aes-1.1.1" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.1.1.tgz";
        sha512 = "0b874c5j68a6h1smd9avnc98zpjy2b4sykkhfpn97lzg7k5aq3ab0jdsmxjafifm0sa3srwscfpcl70gwnlg242p7cavnf115hd6sah";
      };
    };
    "browserify-des-1.0.0" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.0.tgz";
        sha1 = "daa277717470922ed2fe18594118a175439721dd";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 = "1wd18zxd7n42asa63aa4k1bdf58warg29c7c8cdzzkd4r1wva7qwzqnn52h8g8hqwj7bxjkk3ryghajrvz4i27h5bzp30p8hjiqdzgx";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "3cm9kdc1sv7pakzlhrc1pazdvg9lk4hv31lximwbcrgmwfzg6imxrndszgx9yzlizknfh2b73cr7b5mfcv50bldpyq6jr5s4zknsj1a";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "des.js-1.0.0" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.0.tgz";
        sha1 = "c074d2e2aa6a8a9a07dbd61f9a15c2cd83ec8ecc";
      };
    };
    "minimalistic-assert-1.0.0" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.0.tgz";
        sha1 = "702be2dda6b37f4836bcb3f5db56641b64a1d3d3";
      };
    };
    "md5.js-1.3.4" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.4.tgz";
        sha1 = "e9bdbde94a20a5ac18b04340fc5764d5b09d901d";
      };
    };
    "hash-base-3.0.4" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.0.4.tgz";
        sha1 = "5fc8686847ecd73499403319a6b0a3f3f6ae4918";
      };
    };
    "bn.js-4.11.8" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.8.tgz";
        sha512 = "20bg51v29zygy89w84qb64pkjikxfjdsgjs0ry6pvv8fkwn5kd1izrqn022d838q3rcaq8dmy033g7q8b6960j4f8ipan74y9ydimr2";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "elliptic-6.4.0" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.4.0.tgz";
        sha1 = "cac9af8762c85836187003c8dfe193e5e2eae5df";
      };
    };
    "parse-asn1-5.1.0" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.0.tgz";
        sha1 = "37c4f9b7ed3ab65c74817b5f2480937fbf97c712";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "hash.js-1.1.3" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.3.tgz";
        sha512 = "0f88i7rv3ib8lwdh5z5lwrml404frzb1a9n3g25y85jpfng82vzsv7m3c5fbyrpq5ki4c3pa8823z3s61xfigm45q469nqnzp416hgx";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "asn1.js-4.9.2" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.9.2.tgz";
        sha512 = "071d32h5646ddyfxvmm0yd0xc320zh2cdsjal4hs8cs0hgn9dpq7k9c9ndlhjq3y93nlawkinm99znqvp0cxx61ic7qy4nn7d5arwvg";
      };
    };
    "ripemd160-2.0.1" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.1.tgz";
        sha1 = "0f4584295c53a3628af7e6d79aca21ce57d1c6e7";
      };
    };
    "sha.js-2.4.9" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.9.tgz";
        sha512 = "3l96mlw71zgkmfm9madd3jcndrpm2fm4jz2q5gz9mbm27mdg89hsbrg22pfl32ha76xa3pza83m2mc3b47pnq19mz3j6vkasn9dxk0v";
      };
    };
    "hash-base-2.0.2" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-2.0.2.tgz";
        sha1 = "66ea1d856db4e8a5470cadf6fce23ae5244ef2e1";
      };
    };
    "miller-rabin-4.0.1" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.1.tgz";
        sha512 = "12277knznlw4myxmgg6vgkrwmrhj9dyniscrlph3s08ndi2q25v3wrv6rwanvz29v5k5x756xa5yif4xllrghpn3jqaamnr3cp5ypnp";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "38chm1mh077ksx6hy2sssfz4q29hf0ncb9k6ila7si54zqcpl5fxd1rh6wi82blqp7jcspf4aynr7jqhbsg2yc9y42xpqqp6c1jz2n8";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "3kr8dm9qyklmm2xyiz75s8db90bfilfals4x0g276kncihrrrz0ar4y6dqpvc7pwy7h43jay1bayi1r62x97nzvcswkk4ap18pl1irm";
      };
    };
    "lexical-scope-1.2.0" = {
      name = "lexical-scope";
      packageName = "lexical-scope";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lexical-scope/-/lexical-scope-1.2.0.tgz";
        sha1 = "fcea5edc704a4b3a8796cdca419c3a0afaf22df4";
      };
    };
    "astw-2.2.0" = {
      name = "astw";
      packageName = "astw";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/astw/-/astw-2.2.0.tgz";
        sha1 = "7bd41784d32493987aeb239b6b4e1c57a873b917";
      };
    };
    "acorn-4.0.13" = {
      name = "acorn";
      packageName = "acorn";
      version = "4.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz";
        sha1 = "105495ae5361d697bd195c825192e1ad7f253787";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "stream-splicer-2.0.0" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-2.0.0.tgz";
        sha1 = "1b63be438a133e4b671cc1935197600175910d83";
      };
    };
    "detective-4.7.0" = {
      name = "detective";
      packageName = "detective";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-4.7.0.tgz";
        sha512 = "2mx76wpkjn1pabajhcwl4jz35kb1vqhwba3sl90xa625z6gr9cmc8graa5lm35h56arj84jk2gdw1bhsfcl3hwg098ilz2c8x46lq72";
      };
    };
    "stream-combiner2-1.1.1" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.1.1.tgz";
        sha1 = "fb4d8a1420ea362764e21ad4780397bebcb41cbe";
      };
    };
    "acorn-5.2.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.2.1.tgz";
        sha512 = "3ryzhy30vzfnn2a0crafh3qsrx145ali8i88q1bc0lzl1dz0ycmjmmwh2yn9xfjs3vmjxl7nphpwcs4imgz3da5jb8fvjqbrvnjwvcc";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha512 = "22vw5mmwlyblqc2zyqwl39wyhyahhpiyknim8iz5fk6xi002x777gkswiq8fh297djs5ii4pgrys57wq33hr5zf3xfd0d7kjxkzl0g0";
      };
    };
    "path-parse-1.0.5" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz";
        sha1 = "3c1adf871ea9cd6c9431b6ea2bd74a0ff055c4c1";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "array-filter-0.0.1" = {
      name = "array-filter";
      packageName = "array-filter";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-filter/-/array-filter-0.0.1.tgz";
        sha1 = "7da8cf2e26628ed732803581fd21f67cacd2eeec";
      };
    };
    "array-reduce-0.0.0" = {
      name = "array-reduce";
      packageName = "array-reduce";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-reduce/-/array-reduce-0.0.0.tgz";
        sha1 = "173899d3ffd1c7d9383e4479525dbe278cab5f2b";
      };
    };
    "array-map-0.0.0" = {
      name = "array-map";
      packageName = "array-map";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-map/-/array-map-0.0.0.tgz";
        sha1 = "88a2bab73d1cf7bcd5c1b118a003f66f665fa662";
      };
    };
    "builtin-status-codes-3.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-3.0.0.tgz";
        sha1 = "85982878e21b98e1c66425e03d0174788f569ee8";
      };
    };
    "to-arraybuffer-1.0.1" = {
      name = "to-arraybuffer";
      packageName = "to-arraybuffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-arraybuffer/-/to-arraybuffer-1.0.1.tgz";
        sha1 = "7d229b1fcc637e466ca081180836a7aabff83f43";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "JSONStream-0.10.0" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-0.10.0.tgz";
        sha1 = "74349d0d89522b71f30f0a03ff9bd20ca6f12ac0";
      };
    };
    "browserify-cache-api-3.0.1" = {
      name = "browserify-cache-api";
      packageName = "browserify-cache-api";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cache-api/-/browserify-cache-api-3.0.1.tgz";
        sha1 = "96247e853f068fd6e0d45cc73f0bb2cd9778ef02";
      };
    };
    "jsonparse-0.0.5" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-0.0.5.tgz";
        sha1 = "330542ad3f0a654665b778f3eb2d9a9fa507ac64";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha1 = "168a4701756b6a7f51a12ce0c97bfa28c084ed63";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "1x901mk5cdib4xp27v4ivwwr7mhy64r4rk953bzivi5p9lf2bhw88ra2rhkd254xkdx2d3q30zkq239vc4yx4pfsj4hpys8rbr6fif7";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "mute-stream-0.0.7" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz";
        sha1 = "3075ce93bc21b8fab43e1bc4da7e8115ed1e7bab";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "async-2.6.0" = {
      name = "async";
      packageName = "async";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.0.tgz";
        sha512 = "0zp4b5788400npi1ixjry5x3a4m21c8pnknk8v731rgnwnjbp5ijmfcf5ppmn1ap4a04md1s9dr8n9ygdvrmiai590v0k6dby1wc1y4";
      };
    };
    "chokidar-1.7.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz";
        sha1 = "798e689778151c8076b4b360e5edd28cda2bb468";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "anymatch-1.3.2" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-1.3.2.tgz";
        sha512 = "269dbx666z4ws49vag1dma5kdpjlx83s74c1jlngrn2672rhvbc47i5ay5h40spmrzgvbvcm33i4yrp88rrc6lg70v78k155z45lwyi";
      };
    };
    "async-each-1.0.1" = {
      name = "async-each";
      packageName = "async-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-each/-/async-each-1.0.1.tgz";
        sha1 = "19d386a1d9edc6e7c1c85d388aedbcc56d33602d";
      };
    };
    "glob-parent-2.0.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-2.0.0.tgz";
        sha1 = "81383d72db054fcccf5336daa902f182f6edbb28";
      };
    };
    "is-binary-path-1.0.1" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-1.0.1.tgz";
        sha1 = "75f16642b480f187a711c814161fd3a4a7655898";
      };
    };
    "is-glob-2.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-2.0.1.tgz";
        sha1 = "d096f926a3ded5600f3fdfd91198cb0888c2d863";
      };
    };
    "readdirp-2.1.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-2.1.0.tgz";
        sha1 = "4ed0ad060df3073300c48440373f72d1cc642d78";
      };
    };
    "fsevents-1.1.3" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz";
        sha512 = "3jw51f4iayxvp9wfxczk1xgcvhsydhlgah64jmpl0mqiii2h8i5pp0lrqac5xn7296gxqrvy4lgm4k4hkifk8gipgqxd68x764gp2jq";
      };
    };
    "micromatch-2.3.11" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "2.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-2.3.11.tgz";
        sha1 = "86677c97d1720b363431d04d0d15293bd38c1565";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "arr-diff-2.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz";
        sha1 = "8f3b827f955a8bd669697e4a4256ac3ceae356cf";
      };
    };
    "array-unique-0.2.1" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz";
        sha1 = "a1d97ccafcbc2625cc70fadceb36a50c58b01a53";
      };
    };
    "braces-1.8.5" = {
      name = "braces";
      packageName = "braces";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-1.8.5.tgz";
        sha1 = "ba77962e12dff969d6b76711e914b737857bf6a7";
      };
    };
    "expand-brackets-0.1.5" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-0.1.5.tgz";
        sha1 = "df07284e342a807cd733ac5af72411e581d1177b";
      };
    };
    "extglob-0.3.2" = {
      name = "extglob";
      packageName = "extglob";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-0.3.2.tgz";
        sha1 = "2e18ff3d2f49ab2765cec9023f011daa8d8349a1";
      };
    };
    "filename-regex-2.0.1" = {
      name = "filename-regex";
      packageName = "filename-regex";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-regex/-/filename-regex-2.0.1.tgz";
        sha1 = "c1c4b9bee3e09725ddb106b75c1e301fe2f18b26";
      };
    };
    "is-extglob-1.0.0" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-1.0.0.tgz";
        sha1 = "ac468177c4943405a092fc8f29760c6ffc6206c0";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "object.omit-2.0.1" = {
      name = "object.omit";
      packageName = "object.omit";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.omit/-/object.omit-2.0.1.tgz";
        sha1 = "1a9c744829f39dbb858c76ca3579ae2a54ebd1fa";
      };
    };
    "parse-glob-3.0.4" = {
      name = "parse-glob";
      packageName = "parse-glob";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-glob/-/parse-glob-3.0.4.tgz";
        sha1 = "b2c376cfb11f35513badd173ef0bb6e3a388391c";
      };
    };
    "regex-cache-0.4.4" = {
      name = "regex-cache";
      packageName = "regex-cache";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-cache/-/regex-cache-0.4.4.tgz";
        sha512 = "1crfmf19zkv0imnbbkj7bwrcyin3zxa88cs86b6apkxj8qrsmkxnydhsy2ia75q4ld10rhi2s2c36h7g77a997mh9c2z453s311jllx";
      };
    };
    "arr-flatten-1.1.0" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.1.0.tgz";
        sha512 = "2vdly17xk5kw7bfzajrjdnw4ml3wrfblx8064n0i4fxlchcscx2mvnwkq2bnnqvbqvdy4vs9ad462lz0rid7khysly9m9vzjiblly1g";
      };
    };
    "expand-range-1.8.2" = {
      name = "expand-range";
      packageName = "expand-range";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-range/-/expand-range-1.8.2.tgz";
        sha1 = "a299effd335fe2721ebae8e257ec79644fc85337";
      };
    };
    "preserve-0.2.0" = {
      name = "preserve";
      packageName = "preserve";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz";
        sha1 = "815ed1f6ebc65926f865b310c0713bcb3315ce4b";
      };
    };
    "repeat-element-1.1.2" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.2.tgz";
        sha1 = "ef089a178d1483baae4d93eb98b4f9e4e11d990a";
      };
    };
    "fill-range-2.2.3" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-2.2.3.tgz";
        sha1 = "50b77dfd7e469bc7492470963699fe7a8485a723";
      };
    };
    "is-number-2.1.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-2.1.0.tgz";
        sha1 = "01fcbbb393463a548f2f466cce16dece49db908f";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha1 = "f065561096a3f1da2ef46272f815c840d87e0c89";
      };
    };
    "randomatic-1.1.7" = {
      name = "randomatic";
      packageName = "randomatic";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomatic/-/randomatic-1.1.7.tgz";
        sha512 = "2is2kipfnz3hl4yxgqk07rll6956cq3zzf9cddai3f0lij5acq76v98qv14qkpljh1pqfsyb8p69xa9cyaww6p0j91s4vc9zj6594hg";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "is-number-3.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-3.0.0.tgz";
        sha1 = "24fd6201a4782cf50561c810276afc7d12d71195";
      };
    };
    "kind-of-4.0.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-4.0.0.tgz";
        sha1 = "20813df3d712928b207378691a45066fae72dd57";
      };
    };
    "is-posix-bracket-0.1.1" = {
      name = "is-posix-bracket";
      packageName = "is-posix-bracket";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-posix-bracket/-/is-posix-bracket-0.1.1.tgz";
        sha1 = "3334dc79774368e92f016e6fbc0a88f5cd6e6bc4";
      };
    };
    "for-own-0.1.5" = {
      name = "for-own";
      packageName = "for-own";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-0.1.5.tgz";
        sha1 = "5265c681a4f294dabbf17c9509b6763aa84510ce";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "glob-base-0.3.0" = {
      name = "glob-base";
      packageName = "glob-base";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-base/-/glob-base-0.3.0.tgz";
        sha1 = "dbb164f6221b1c0b1ccf82aea328b497df0ea3c4";
      };
    };
    "is-dotfile-1.0.3" = {
      name = "is-dotfile";
      packageName = "is-dotfile";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-dotfile/-/is-dotfile-1.0.3.tgz";
        sha1 = "a6a2f32ffd2dfb04f5ca25ecd0f6b83cf798a1e1";
      };
    };
    "is-equal-shallow-0.1.3" = {
      name = "is-equal-shallow";
      packageName = "is-equal-shallow";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-equal-shallow/-/is-equal-shallow-0.1.3.tgz";
        sha1 = "2238098fc221de0bcfa5d9eac4c45d638aa1c534";
      };
    };
    "is-primitive-2.0.0" = {
      name = "is-primitive";
      packageName = "is-primitive";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-primitive/-/is-primitive-2.0.0.tgz";
        sha1 = "207bab91638499c07b2adf240a41a87210034575";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "binary-extensions-1.11.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-1.11.0.tgz";
        sha1 = "46aa1751fb6a2f93ee5e689bb1087d4b14c6c205";
      };
    };
    "set-immediate-shim-1.0.1" = {
      name = "set-immediate-shim";
      packageName = "set-immediate-shim";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-immediate-shim/-/set-immediate-shim-1.0.1.tgz";
        sha1 = "4b2b1b27eb808a9f8dcc481a58e5e56f599f3f61";
      };
    };
    "nan-2.8.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.8.0.tgz";
        sha1 = "ed715f3fe9de02b57a5e6252d90a96675e1f085a";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
  };
in
{
  pulp = nodeEnv.buildNodePackage {
    name = "pulp";
    packageName = "pulp";
    version = "12.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/pulp/-/pulp-12.0.1.tgz";
      sha512 = "3n09lgnyd4p3h3jlhgcvbh6n6m9h89hwvbhli5ic32fkl5y4g7yi61m1vw483479jxkif2zyqs89l6j6hq4iy15jdknx1lcp9qbyvwy";
    };
    dependencies = [
      (sources."browserify-13.3.0" // {
        dependencies = [
          (sources."JSONStream-1.3.2" // {
            dependencies = [
              sources."jsonparse-1.3.1"
            ];
          })
          sources."assert-1.4.1"
          (sources."browser-pack-6.0.2" // {
            dependencies = [
              (sources."combine-source-map-0.7.2" // {
                dependencies = [
                  sources."convert-source-map-1.1.3"
                  sources."inline-source-map-0.6.2"
                  sources."lodash.memoize-3.0.4"
                  sources."source-map-0.5.7"
                ];
              })
              sources."umd-3.0.1"
            ];
          })
          (sources."browser-resolve-1.11.2" // {
            dependencies = [
              sources."resolve-1.1.7"
            ];
          })
          (sources."browserify-zlib-0.1.4" // {
            dependencies = [
              sources."pako-0.2.9"
            ];
          })
          (sources."buffer-4.9.1" // {
            dependencies = [
              sources."base64-js-1.2.1"
              sources."ieee754-1.1.8"
              sources."isarray-1.0.0"
            ];
          })
          sources."cached-path-relative-1.0.1"
          (sources."concat-stream-1.5.2" // {
            dependencies = [
              sources."typedarray-0.0.6"
              (sources."readable-stream-2.0.6" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          (sources."console-browserify-1.1.0" // {
            dependencies = [
              sources."date-now-0.1.4"
            ];
          })
          sources."constants-browserify-1.0.0"
          (sources."crypto-browserify-3.12.0" // {
            dependencies = [
              (sources."browserify-cipher-1.0.0" // {
                dependencies = [
                  (sources."browserify-aes-1.1.1" // {
                    dependencies = [
                      sources."buffer-xor-1.0.3"
                      sources."cipher-base-1.0.4"
                      sources."safe-buffer-5.1.1"
                    ];
                  })
                  (sources."browserify-des-1.0.0" // {
                    dependencies = [
                      (sources."cipher-base-1.0.4" // {
                        dependencies = [
                          sources."safe-buffer-5.1.1"
                        ];
                      })
                      (sources."des.js-1.0.0" // {
                        dependencies = [
                          sources."minimalistic-assert-1.0.0"
                        ];
                      })
                    ];
                  })
                  (sources."evp_bytestokey-1.0.3" // {
                    dependencies = [
                      (sources."md5.js-1.3.4" // {
                        dependencies = [
                          sources."hash-base-3.0.4"
                        ];
                      })
                      sources."safe-buffer-5.1.1"
                    ];
                  })
                ];
              })
              (sources."browserify-sign-4.0.4" // {
                dependencies = [
                  sources."bn.js-4.11.8"
                  sources."browserify-rsa-4.0.1"
                  (sources."elliptic-6.4.0" // {
                    dependencies = [
                      sources."brorand-1.1.0"
                      sources."hash.js-1.1.3"
                      sources."hmac-drbg-1.0.1"
                      sources."minimalistic-assert-1.0.0"
                      sources."minimalistic-crypto-utils-1.0.1"
                    ];
                  })
                  (sources."parse-asn1-5.1.0" // {
                    dependencies = [
                      (sources."asn1.js-4.9.2" // {
                        dependencies = [
                          sources."minimalistic-assert-1.0.0"
                        ];
                      })
                      (sources."browserify-aes-1.1.1" // {
                        dependencies = [
                          sources."buffer-xor-1.0.3"
                          sources."cipher-base-1.0.4"
                          sources."safe-buffer-5.1.1"
                        ];
                      })
                      (sources."evp_bytestokey-1.0.3" // {
                        dependencies = [
                          (sources."md5.js-1.3.4" // {
                            dependencies = [
                              sources."hash-base-3.0.4"
                            ];
                          })
                          sources."safe-buffer-5.1.1"
                        ];
                      })
                    ];
                  })
                ];
              })
              (sources."create-ecdh-4.0.0" // {
                dependencies = [
                  sources."bn.js-4.11.8"
                  (sources."elliptic-6.4.0" // {
                    dependencies = [
                      sources."brorand-1.1.0"
                      sources."hash.js-1.1.3"
                      sources."hmac-drbg-1.0.1"
                      sources."minimalistic-assert-1.0.0"
                      sources."minimalistic-crypto-utils-1.0.1"
                    ];
                  })
                ];
              })
              (sources."create-hash-1.1.3" // {
                dependencies = [
                  (sources."cipher-base-1.0.4" // {
                    dependencies = [
                      sources."safe-buffer-5.1.1"
                    ];
                  })
                  (sources."ripemd160-2.0.1" // {
                    dependencies = [
                      sources."hash-base-2.0.2"
                    ];
                  })
                  (sources."sha.js-2.4.9" // {
                    dependencies = [
                      sources."safe-buffer-5.1.1"
                    ];
                  })
                ];
              })
              (sources."create-hmac-1.1.6" // {
                dependencies = [
                  sources."cipher-base-1.0.4"
                  (sources."ripemd160-2.0.1" // {
                    dependencies = [
                      sources."hash-base-2.0.2"
                    ];
                  })
                  sources."safe-buffer-5.1.1"
                  sources."sha.js-2.4.9"
                ];
              })
              (sources."diffie-hellman-5.0.2" // {
                dependencies = [
                  sources."bn.js-4.11.8"
                  (sources."miller-rabin-4.0.1" // {
                    dependencies = [
                      sources."brorand-1.1.0"
                    ];
                  })
                ];
              })
              (sources."pbkdf2-3.0.14" // {
                dependencies = [
                  (sources."ripemd160-2.0.1" // {
                    dependencies = [
                      sources."hash-base-2.0.2"
                    ];
                  })
                  sources."safe-buffer-5.1.1"
                  sources."sha.js-2.4.9"
                ];
              })
              (sources."public-encrypt-4.0.0" // {
                dependencies = [
                  sources."bn.js-4.11.8"
                  sources."browserify-rsa-4.0.1"
                  (sources."parse-asn1-5.1.0" // {
                    dependencies = [
                      (sources."asn1.js-4.9.2" // {
                        dependencies = [
                          sources."minimalistic-assert-1.0.0"
                        ];
                      })
                      (sources."browserify-aes-1.1.1" // {
                        dependencies = [
                          sources."buffer-xor-1.0.3"
                          sources."cipher-base-1.0.4"
                          sources."safe-buffer-5.1.1"
                        ];
                      })
                      (sources."evp_bytestokey-1.0.3" // {
                        dependencies = [
                          (sources."md5.js-1.3.4" // {
                            dependencies = [
                              sources."hash-base-3.0.4"
                            ];
                          })
                          sources."safe-buffer-5.1.1"
                        ];
                      })
                    ];
                  })
                ];
              })
              (sources."randombytes-2.0.5" // {
                dependencies = [
                  sources."safe-buffer-5.1.1"
                ];
              })
              (sources."randomfill-1.0.3" // {
                dependencies = [
                  sources."safe-buffer-5.1.1"
                ];
              })
            ];
          })
          sources."defined-1.0.0"
          sources."deps-sort-2.0.0"
          sources."domain-browser-1.1.7"
          sources."duplexer2-0.1.4"
          sources."events-1.1.1"
          (sources."has-1.0.1" // {
            dependencies = [
              sources."function-bind-1.1.1"
            ];
          })
          sources."htmlescape-1.1.1"
          sources."https-browserify-0.0.1"
          sources."inherits-2.0.3"
          (sources."insert-module-globals-7.0.1" // {
            dependencies = [
              (sources."combine-source-map-0.7.2" // {
                dependencies = [
                  sources."convert-source-map-1.1.3"
                  sources."inline-source-map-0.6.2"
                  sources."lodash.memoize-3.0.4"
                  sources."source-map-0.5.7"
                ];
              })
              sources."is-buffer-1.1.6"
              (sources."lexical-scope-1.2.0" // {
                dependencies = [
                  (sources."astw-2.2.0" // {
                    dependencies = [
                      sources."acorn-4.0.13"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."labeled-stream-splicer-2.0.0" // {
            dependencies = [
              sources."isarray-0.0.1"
              sources."stream-splicer-2.0.0"
            ];
          })
          (sources."module-deps-4.1.1" // {
            dependencies = [
              (sources."detective-4.7.0" // {
                dependencies = [
                  sources."acorn-5.2.1"
                ];
              })
              sources."stream-combiner2-1.1.1"
            ];
          })
          sources."os-browserify-0.1.2"
          (sources."parents-1.0.1" // {
            dependencies = [
              sources."path-platform-0.11.15"
            ];
          })
          sources."path-browserify-0.0.0"
          sources."process-0.11.10"
          sources."punycode-1.4.1"
          sources."querystring-es3-0.2.1"
          sources."read-only-stream-2.0.0"
          (sources."readable-stream-2.3.3" // {
            dependencies = [
              sources."core-util-is-1.0.2"
              sources."isarray-1.0.0"
              sources."process-nextick-args-1.0.7"
              sources."safe-buffer-5.1.1"
              sources."string_decoder-1.0.3"
              sources."util-deprecate-1.0.2"
            ];
          })
          (sources."resolve-1.5.0" // {
            dependencies = [
              sources."path-parse-1.0.5"
            ];
          })
          (sources."shasum-1.0.2" // {
            dependencies = [
              (sources."json-stable-stringify-0.0.1" // {
                dependencies = [
                  sources."jsonify-0.0.0"
                ];
              })
              (sources."sha.js-2.4.9" // {
                dependencies = [
                  sources."safe-buffer-5.1.1"
                ];
              })
            ];
          })
          (sources."shell-quote-1.6.1" // {
            dependencies = [
              sources."jsonify-0.0.0"
              sources."array-filter-0.0.1"
              sources."array-reduce-0.0.0"
              sources."array-map-0.0.0"
            ];
          })
          sources."stream-browserify-2.0.1"
          (sources."stream-http-2.7.2" // {
            dependencies = [
              sources."builtin-status-codes-3.0.0"
              sources."to-arraybuffer-1.0.1"
            ];
          })
          sources."string_decoder-0.10.31"
          (sources."subarg-1.0.0" // {
            dependencies = [
              sources."minimist-1.2.0"
            ];
          })
          (sources."syntax-error-1.3.0" // {
            dependencies = [
              sources."acorn-4.0.13"
            ];
          })
          sources."through2-2.0.3"
          sources."timers-browserify-1.4.2"
          sources."tty-browserify-0.0.0"
          (sources."url-0.11.0" // {
            dependencies = [
              sources."punycode-1.3.2"
              sources."querystring-0.2.0"
            ];
          })
          (sources."util-0.10.3" // {
            dependencies = [
              sources."inherits-2.0.1"
            ];
          })
          (sources."vm-browserify-0.0.4" // {
            dependencies = [
              sources."indexof-0.0.1"
            ];
          })
          sources."xtend-4.0.1"
        ];
      })
      (sources."browserify-incremental-3.1.1" // {
        dependencies = [
          (sources."JSONStream-0.10.0" // {
            dependencies = [
              sources."jsonparse-0.0.5"
            ];
          })
          (sources."browserify-cache-api-3.0.1" // {
            dependencies = [
              sources."async-1.5.2"
            ];
          })
          (sources."through2-2.0.3" // {
            dependencies = [
              (sources."readable-stream-2.3.3" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."inherits-2.0.3"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."safe-buffer-5.1.1"
                  sources."string_decoder-1.0.3"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          sources."xtend-4.0.1"
        ];
      })
      (sources."concat-stream-1.6.0" // {
        dependencies = [
          sources."inherits-2.0.3"
          sources."typedarray-0.0.6"
          (sources."readable-stream-2.3.3" // {
            dependencies = [
              sources."core-util-is-1.0.2"
              sources."isarray-1.0.0"
              sources."process-nextick-args-1.0.7"
              sources."safe-buffer-5.1.1"
              sources."string_decoder-1.0.3"
              sources."util-deprecate-1.0.2"
            ];
          })
        ];
      })
      (sources."glob-7.1.2" // {
        dependencies = [
          sources."fs.realpath-1.0.0"
          (sources."inflight-1.0.6" // {
            dependencies = [
              sources."wrappy-1.0.2"
            ];
          })
          sources."inherits-2.0.3"
          (sources."once-1.4.0" // {
            dependencies = [
              sources."wrappy-1.0.2"
            ];
          })
          sources."path-is-absolute-1.0.1"
        ];
      })
      (sources."minimatch-3.0.4" // {
        dependencies = [
          (sources."brace-expansion-1.1.8" // {
            dependencies = [
              sources."balanced-match-1.0.0"
              sources."concat-map-0.0.1"
            ];
          })
        ];
      })
      (sources."node-static-0.7.10" // {
        dependencies = [
          (sources."optimist-0.6.1" // {
            dependencies = [
              sources."wordwrap-0.0.3"
              sources."minimist-0.0.10"
            ];
          })
          sources."colors-1.1.2"
          sources."mime-1.6.0"
        ];
      })
      (sources."read-1.0.7" // {
        dependencies = [
          sources."mute-stream-0.0.7"
        ];
      })
      sources."string-stream-0.0.7"
      (sources."temp-0.8.3" // {
        dependencies = [
          sources."os-tmpdir-1.0.2"
          sources."rimraf-2.2.8"
        ];
      })
      sources."through-2.3.8"
      sources."tree-kill-1.2.0"
      (sources."watchpack-1.4.0" // {
        dependencies = [
          (sources."async-2.6.0" // {
            dependencies = [
              sources."lodash-4.17.4"
            ];
          })
          (sources."chokidar-1.7.0" // {
            dependencies = [
              (sources."anymatch-1.3.2" // {
                dependencies = [
                  (sources."micromatch-2.3.11" // {
                    dependencies = [
                      (sources."arr-diff-2.0.0" // {
                        dependencies = [
                          sources."arr-flatten-1.1.0"
                        ];
                      })
                      sources."array-unique-0.2.1"
                      (sources."braces-1.8.5" // {
                        dependencies = [
                          (sources."expand-range-1.8.2" // {
                            dependencies = [
                              (sources."fill-range-2.2.3" // {
                                dependencies = [
                                  sources."is-number-2.1.0"
                                  (sources."isobject-2.1.0" // {
                                    dependencies = [
                                      sources."isarray-1.0.0"
                                    ];
                                  })
                                  (sources."randomatic-1.1.7" // {
                                    dependencies = [
                                      (sources."is-number-3.0.0" // {
                                        dependencies = [
                                          (sources."kind-of-3.2.2" // {
                                            dependencies = [
                                              sources."is-buffer-1.1.6"
                                            ];
                                          })
                                        ];
                                      })
                                      (sources."kind-of-4.0.0" // {
                                        dependencies = [
                                          sources."is-buffer-1.1.6"
                                        ];
                                      })
                                    ];
                                  })
                                  sources."repeat-string-1.6.1"
                                ];
                              })
                            ];
                          })
                          sources."preserve-0.2.0"
                          sources."repeat-element-1.1.2"
                        ];
                      })
                      (sources."expand-brackets-0.1.5" // {
                        dependencies = [
                          sources."is-posix-bracket-0.1.1"
                        ];
                      })
                      sources."extglob-0.3.2"
                      sources."filename-regex-2.0.1"
                      sources."is-extglob-1.0.0"
                      (sources."kind-of-3.2.2" // {
                        dependencies = [
                          sources."is-buffer-1.1.6"
                        ];
                      })
                      (sources."object.omit-2.0.1" // {
                        dependencies = [
                          (sources."for-own-0.1.5" // {
                            dependencies = [
                              sources."for-in-1.0.2"
                            ];
                          })
                          sources."is-extendable-0.1.1"
                        ];
                      })
                      (sources."parse-glob-3.0.4" // {
                        dependencies = [
                          sources."glob-base-0.3.0"
                          sources."is-dotfile-1.0.3"
                        ];
                      })
                      (sources."regex-cache-0.4.4" // {
                        dependencies = [
                          (sources."is-equal-shallow-0.1.3" // {
                            dependencies = [
                              sources."is-primitive-2.0.0"
                            ];
                          })
                        ];
                      })
                    ];
                  })
                  (sources."normalize-path-2.1.1" // {
                    dependencies = [
                      sources."remove-trailing-separator-1.1.0"
                    ];
                  })
                ];
              })
              sources."async-each-1.0.1"
              sources."glob-parent-2.0.0"
              sources."inherits-2.0.3"
              (sources."is-binary-path-1.0.1" // {
                dependencies = [
                  sources."binary-extensions-1.11.0"
                ];
              })
              (sources."is-glob-2.0.1" // {
                dependencies = [
                  sources."is-extglob-1.0.0"
                ];
              })
              sources."path-is-absolute-1.0.1"
              (sources."readdirp-2.1.0" // {
                dependencies = [
                  (sources."readable-stream-2.3.3" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                      sources."isarray-1.0.0"
                      sources."process-nextick-args-1.0.7"
                      sources."safe-buffer-5.1.1"
                      sources."string_decoder-1.0.3"
                      sources."util-deprecate-1.0.2"
                    ];
                  })
                  sources."set-immediate-shim-1.0.1"
                ];
              })
              (sources."fsevents-1.1.3" // {
                dependencies = [
                  sources."nan-2.8.0"
                ];
              })
            ];
          })
          sources."graceful-fs-4.1.11"
        ];
      })
      (sources."which-1.3.0" // {
        dependencies = [
          sources."isexe-2.0.0"
        ];
      })
      sources."wordwrap-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A build system for PureScript projects";
      homepage = https://github.com/bodil/pulp;
      license = "LGPL-3.0+";
    };
    production = true;
  };
}